### ISSUE TITLE
Hello? TheRealAvci? Are you there?

### ISSUE THREAD

**Issue by tarkan809** [Animelici804/Mushroom-Bot#1]
Sorry for my delay. But... where were you? I looked on gamejolt that your account is gone!

Can you please tell me what happened?

(BTW I'm tarkan809 from gamejolt) (Sorry if I post an issue here because I couldn't find you on gamejolt.)

**Comment by tarkan809** [comment]
Nevermind... I found you. @Animelici804

**Comment by Animelici804** [comment]
Nope, my account isn't gone.

**Comment by Animelici804** [comment]
I just changed the name for people to mention me correctly.
